### PR TITLE
some modifications for yang module

### PR DESCRIPTION
**Pull request by haknmcaobin**
1.add AK Cert type; 
2.add device-info as a optional container;
3. add some useful attributes in tpms list; 
4.add node-name/location in compute-node list; 
5.encompass tpm list in compute-node list; 
6.add LAK public structure;

### CODE REVIEW

**Comment by shwethab** [comment]
Can you justify adding device-info as a container in this model? Why overload this model with device software/hardware inventory? There are dedicated models to query device info

**Comment by haknmcaobin** [comment]
> Can you justify adding device-info as a container in this model? Why overload this model with device software/hardware inventory? There are dedicated models to query device info

Hi, adding a optional device-info container in this model is used to fetch device info in some scenario without a dedicated device-management model.

**Comment by shwethab** [comment]
>optional device-info container in this model is used to fetch device info in some scenario without a dedicated device-management model.

Even in absence of a device management any entity that queries this model can pull any other models for additional information about the network element. This model IMHO should strictly deal with data pertaining to attestation

**Review by shwethab — CHANGES_REQUESTED** [review]
I think minus the device-info the changes are ready to merge

**Comment by haknmcaobin** [comment]
> I think minus the device-info the changes are ready to merge

Thanks for your review :)
If we use dedicated module to query device info, should we use ietf-hardware.yang or other yang model?

**Comment by henkbirkholz** [comment]
Only nits remain. Corresponding issue opened. Merging this one.

**Pull request merged**
